### ISSUE TITLE
Exception in API < 20 when loading plus vector

### ISSUE THREAD

**Issue by EmmanuelMess** [jahirfiquitiva/FABsMenu#27]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of FABsMenu.

###### Device/library info:
 - FABsMenu version: `1.1.1`
 - Device OS version: `API 19`
 - Device Manufacturer: `Android Virtual Device`
 - Device Name: `Nexus One`

###### Reproduction Steps

1. Open app with lib in API 19 or lower
2. Stack trace can be read in logcat and `floatingActionButton.getMenuButton()` is null.

###### Expected Result

`floatingActionButton.getMenuButton()` should not be null.

###### Actual Result

`floatingActionButton.getMenuButton()` is null.
And stack trace in logcat:
```gradle
W/System.err: android.content.res.Resources$NotFoundException: File res/drawable/ic_add_white_24dp.xml from drawable resource ID #0x7f080071
W/System.err:     at android.content.res.Resources.loadDrawable(Resources.java:2101)
W/System.err:     at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
W/System.err:     at jahirfiquitiva.libs.fabsmenu.FABsMenu.init(FABsMenu.java:152)
W/System.err:     at jahirfiquitiva.libs.fabsmenu.FABsMenu.<init>(FABsMenu.java:106)
W/System.err:     at java.lang.reflect.Constructor.constructNative(Native Method)
W/System.err:     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:595)
W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:697)
W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:756)
W/System.err:     at android.view.LayoutInflater.parseInclude(LayoutInflater.java:840)
W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:759)
W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
W/System.err:     at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
W/System.err:     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
W/System.err:     at com.amaze.filemanager.activities.MainActivity.onCreate(MainActivity.java:337)
W/System.err:     at android.app.Activity.performCreate(Activity.java:5231)
W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
W/System.err:     at android.app.ActivityThread.access$800(ActivityThread.java:135)
W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err:     at android.os.Looper.loop(Looper.java:136)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5017)
W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
W/System.err:     at dalvik.system.NativeStart.main(Native Method)
W/System.err: Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #0: invalid drawable tag vector
W/System.err:     at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
W/System.err:     at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
W/System.err:     at android.content.res.Resources.loadDrawable(Resources.java:2097)
W/System.err: 	... 31 more
```

**Comment by jahirfiquitiva** [comment]
Have you enabled vector drawables support in your `build.gradle` file?

```groovy
android {  
   defaultConfig {  
     vectorDrawables.useSupportLibrary = true  
    }  
 }  
```

**Comment by EmmanuelMess** [comment]
[Yes](https://github.com/TeamAmaze/AmazeFileManager/blob/03e89694fdfb701cc67baa2a93f60ba5c3cad356/app/build.gradle#L31).

**Comment by EmmanuelMess** [comment]
Any news? Should I help?

**Comment by leinardi** [comment]
Hi @EmmanuelMess, I made a PR that fix this issue.

@jahirfiquitiva if you have time please have a look.

PS
Your file manager is awesome! Thanks for making it open source :heart:.
